
package eu.europa.ec.markt.dss.ws.validation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This is a test of documentation for ValidationService.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidationService", targetNamespace = "http://ws.dss.markt.ec.europa.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidationService {


    /**
     * This is a test documentation for ValidationService validate document method.
     * 
     * @param document
     * @param diagnosticDataToBeReturned
     * @param policy
     * @param externalContent
     * @return
     *     returns eu.europa.ec.markt.dss.ws.validation.WsValidationReport
     * @throws DSSException_Exception
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "validateDocument", targetNamespace = "http://ws.dss.markt.ec.europa.eu/", className = "eu.europa.ec.markt.dss.ws.validation.ValidateDocument")
    @ResponseWrapper(localName = "validateDocumentResponse", targetNamespace = "http://ws.dss.markt.ec.europa.eu/", className = "eu.europa.ec.markt.dss.ws.validation.ValidateDocumentResponse")
    public WsValidationReport validateDocument(
        @WebParam(name = "document", targetNamespace = "")
        WsDocument document,
        @WebParam(name = "externalContent", targetNamespace = "")
        WsDocument externalContent,
        @WebParam(name = "policy", targetNamespace = "")
        WsDocument policy,
        @WebParam(name = "diagnosticDataToBeReturned", targetNamespace = "")
        boolean diagnosticDataToBeReturned)
        throws DSSException_Exception
    ;

}
